# Generated by Django 5.1.3 on 2025-01-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogarea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='userUploadedImages/'),
        ),
    ]
