# Generated by Django 5.1.3 on 2025-01-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogarea', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail/'),
        ),
    ]
