# Generated by Django 5.1.3 on 2025-01-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogarea', '0009_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Gaming', 'Gaming'), ('Literature', 'Literature'), ('Superhero', 'Superhero'), ('Coding Tutorials', 'Coding Tutorials')], default='Uncategorized', max_length=255),
        ),
    ]
