# Generated by Django 5.1.3 on 2025-01-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogarea', '0010_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail/'),
        ),
    ]
