# Generated by Django 5.1.3 on 2025-01-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogarea', '0011_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='thumbnail.jpg', null=True, upload_to='thumbnail/'),
        ),
    ]
