# Generated by Django 5.1.3 on 2025-01-18 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogarea', '0014_hashtag_post_hashtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hashtags',
        ),
        migrations.DeleteModel(
            name='Hashtag',
        ),
    ]
