# Generated by Django 5.1.3 on 2025-01-18 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogarea', '0018_alter_post_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
