# Generated by Django 5.1.3 on 2025-01-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogarea', '0019_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='articleSnippet',
            field=models.CharField(default='Default Article Snippet', max_length=150),
        ),
    ]
