# Generated by Django 5.1.3 on 2025-01-19 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogarea', '0023_profile_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile',
            new_name='profileImage',
        ),
    ]
