# Generated by Django 5.1.3 on 2025-01-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogarea', '0024_rename_profile_profile_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instagram_link',
            field=models.URLField(blank=True, default='https://instagram.com/', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_link',
            field=models.URLField(blank=True, default='https://x.com/', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube_link',
            field=models.URLField(blank=True, default='https://youtube.com/', null=True),
        ),
    ]
