# Generated by Django 5.1.3 on 2025-01-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogarea', '0025_profile_instagram_link_profile_twitter_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='Earth', max_length=150, null=True),
        ),
    ]
