# Generated by Django 5.1.3 on 2025-01-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogarea', '0026_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='industry',
            field=models.CharField(blank=True, default='Industry', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, default='Occupation', max_length=50, null=True),
        ),
    ]
