# Generated by Django 5.1.3 on 2025-01-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogarea', '0027_profile_industry_profile_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profileBackground',
            field=models.ImageField(blank=True, null=True, upload_to='profile_background'),
        ),
    ]
