# Generated by Django 5.1.3 on 2025-02-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogarea', '0028_profile_profilebackground'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, default='position', max_length=50, null=True),
        ),
    ]
