# Generated by Django 5.1.3 on 2025-02-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogarea', '0029_profile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blogcaption',
            field=models.CharField(blank=True, default='Former Adventurer turned full-time Dad moonlighting as an author', max_length=150, null=True),
        ),
    ]
