# Generated by Django 5.1.3 on 2025-02-11 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogarea', '0034_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
