# Generated by Django 5.1.3 on 2025-02-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogarea', '0036_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True, help_text='Enter your skills separated by commas', null=True),
        ),
    ]
