# Generated by Django 5.1.3 on 2025-02-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogarea', '0037_profile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
    ]
