# Generated by Django 5.1.3 on 2025-02-12 11:03

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogarea', '0038_profile_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
