# Generated by Django 5.1.3 on 2025-02-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogarea', '0041_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='thumbnail/thumbnail.jpg', null=True, upload_to='thumbnail/'),
        ),
    ]
