# Generated by Django 5.1.3 on 2025-02-22 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogarea', '0043_reply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, default=0, related_name='liked_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
