# Generated by Django 5.1.3 on 2025-02-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogarea', '0044_alter_comment_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='articleSnippet',
            field=models.CharField(default='Default Article Snippet', max_length=50),
        ),
    ]
