# Generated by Django 5.1.3 on 2025-02-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogarea', '0046_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
