# Generated by Django 5.1.3 on 2025-02-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogarea', '0047_post_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
