# Generated by Django 5.1.3 on 2025-02-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogarea', '0050_alter_hashtag_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='posts', to='blogarea.hashtag'),
        ),
    ]
