# Generated by Django 5.1.3 on 2025-02-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogarea', '0051_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='about',
            field=models.CharField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit.!', max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='thumbnail/thumbnail.jpg', null=True, upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('News', 'News'), ('Entertainment & Pop Culture', 'Entertainment & Pop Culture'), ('Health & Wellness', 'Health & Wellness'), ('Business & Finance', 'Business & Finance'), ('Education & Learning', 'Education & Learning'), ('Travel & Adventure', 'Travel & Adventure'), ('Recipes', 'Recipes'), ('Science & Nature', 'Science & Nature'), ('Programming', 'Programming'), ('AI', 'AI')], default='Uncategorized', max_length=255),
        ),
    ]
