# Generated by Django 5.1.3 on 2025-03-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogarea', '0052_category_about_category_image_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(blank=True, default='default_profile_pic.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
